name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build frontend
      run: mvn clean install -pl :morci-travel-frontend
    - name: Build backend
      run: mvn clean test package -pl :morci-travel-api
    - name: Run script
      run: ls $GITHUB_WORKSPACE

#    - name: Copy file to server
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
#        port: ${{ secrets.PORT }}
#        source:
#        target:
