name: MorciTravel CI

on: [push]

jobs:

  unit_and_integration_tests:
    name: Unit and Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Test frontend
        run: mvn -B clean install -pl :morci-travel-frontend
      - name: Test backend
        run: mvn -B clean test -pl :morci-travel-api

  package:
    name: Package
    needs: unit_and_integration_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Package backend
        run: mvn -B clean package -Dmaven.test.skip=true -pl :morci-travel-api

  deploy:
    name: Deploy
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ github.workspace }}/morci-travel-api/target/morci-travel-api-0.0.1.jar
          target: "morci-travel-app"
          strip_components: 4
